services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./volume/pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'supertokens']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge
