import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ProgressProvider } from '@bprogress/next/app'
import { QueryClientProviderWrapper } from '@/components/providers/query-client-provider'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ProgressProvider height="3px" color="#22c55e" options={{ showSpinner: false }}>
          <QueryClientProviderWrapper>{children}</QueryClientProviderWrapper>
        </ProgressProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
