import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

import { QueryClientProviderWrapper } from '@/components/providers/query-client-provider'
import { ProgressProviderWrapper } from "@/components/providers/bprogress-provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ProgressProviderWrapper>
          <QueryClientProviderWrapper>
            {children}
          </QueryClientProviderWrapper>
        </ProgressProviderWrapper>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
